### ISSUE TITLE
Feature: Model Serving 

### ISSUE THREAD

**Issue by rapidrabbit76** [rapidrabbit76/Classification-For-Everyone#14]
# Description
프론트 작업전 각 모델 별 추론 서버 구성 

# TODO 
- [ ] Model 2 BentoML packing script
- [ ] BentoML Docker로 말기 
    - [ ] CPU
    - [ ] GPU
- [ ] Model Update 방식 고민

**Comment by zkdlfrlwl2** [comment]
보통 model update는 어떤 식으로 이루어짐 ?

**Comment by rapidrabbit76** [comment]
> 보통 model update는 어떤 식으로 이루어짐 ?

서비스마다 제각각 일거 같은데 ?? 
나도 이제 학교 졸업하고 나온케이스라서 ㅠㅠ 

이번에는 BentoML 서서 모델이랑 같이 컨테이너로 만들어서 배포하고 
k8s 에서 이미지 테그로 업데이트하려고 

내가 했던 경험으로는 자동채색 할때나 석사때 외주작업 할때는 flask로 모델 이랑 같이 컨테이너로 만들어서 했었지
